### ISSUE TITLE
Project search option not highlighting. 

### ISSUE THREAD

**Issue by Lillam** [bxxf/snowflake-zed#1]
First of all; Just wanna say that this is probably my favourite theme that I've come across to date. I fell in love with the style immediately; however, when project searching the option which I'm on when pressing up or down isn't being highlighted so I don't know what option I'm on 🙏 

![Screenshot 2024-05-16 at 21 13 53](https://github.com/bxxf/snowflake-zed/assets/33435522/50247cee-cf95-4cb7-8023-a1a1faf73cd1)

**Comment by bxxf** [comment]
Hi, thank you for your feedback! This will be fixed in https://github.com/zed-industries/extensions/pull/740 PR with couple new theme variants :)
